<a href="https://colab.research.google.com/github/mukulvarshney09/EDA_Revision/blob/main/Data_Cleaning2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [5]:
d2 = pd.read_csv("blood_pressure.csv")

In [6]:
d2

     patient     sex agegrp  bp_before  bp_after
0          1    Male  30-45        143       153
1          2    Male  30-45        163       170
2          3    Male  30-45        153       168
3          4    Male  30-45        153       142
4          5    Male  30-45        146       141
..       ...     ...    ...        ...       ...
115      116  Female    60+        152       152
116      117  Female    60+        161       152
117      118  Female    60+        165       174
118      119  Female    60+        149       151
119      120  Female    60+        185       163

[120 rows x 5 columns]

In [7]:
d2.columns

Index(['patient', 'sex', 'agegrp', 'bp_before', 'bp_after'], dtype='object')

In [8]:
d2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   patient    120 non-null    int64
 1   sex        120 non-null    object
 2   agegrp     120 non-null    object
 3   bp_before  120 non-null    int64
 4   bp_after   120 non-null    int64
dtypes: int64(3), object(2)
memory usage: 4.8+ KB

In [9]:
d2.isnull().sum()

patient      0
sex          0
agegrp       0
bp_before    0
bp_after     0
dtype: int64

In [ ]:
#working on chile data - seems interesting

In [10]:
d3 = pd.read_csv("Chile.csv")

In [11]:
d3

,Unnamed: 0,region,population,sex,age,education,income,statusquo,vote
0,1,N,175000,M,65.0,P,35000.0,1.00820,Y
1,2,N,175000,M,29.0,PS,7500.0,-1.29617,N
2,3,N,175000,F,38.0,P,15000.0,1.23072,Y
3,4,N,175000,F,49.0,P,35000.0,-1.03163,N
4,5,N,175000,F,23.0,S,35000.0,-1.10496,N
...,...,...,...,...,...,...,...,...,...
2695,2696,M,15000,M,42.0,P,15000.0,-1.26247,N
2696,2697,M,15000,F,28.0,P,15000.0,1.32950,Y
2697,2698,M,15000,F,44.0,P,75000.0,1.42045,Y
2698,2699,M,15000,M,21.0,S,75000.0,0.18315,NaN
2699,2700,M,15000,M,20.0,PS,35000.0,1.38179,Y

In [12]:
d3.head(3)

   Unnamed: 0 region  population sex   age education   income  statusquo vote
0           1      N      175000   M  65.0         P  35000.0    1.00820    Y
1           2      N      175000   M  29.0        PS   7500.0   -1.29617    N
2           3      N      175000   F  38.0         P  15000.0    1.23072    Y

In [13]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2700 entries, 0 to 2699
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2700 non-null   int64
 1   region      2700 non-null   object
 2   population  2700 non-null   int64
 3   sex         2700 non-null   object
 4   age         2699 non-null   float64
 5   education   2689 non-null   object
 6   income      2602 non-null   float64
 7   statusquo   2683 non-null   float64
 8   vote        2532 non-null   object
dtypes: float64(3), int64(2), object(4)
memory usage: 190.0+ KB

In [15]:
d3.drop("Unnamed: 0", axis = 1, inplace = True)

In [16]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2700 entries, 0 to 2699
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      2700 non-null   object
 1   population  2700 non-null   int64
 2   sex         2700 non-null   object
 3   age         2699 non-null   float64
 4   education   2689 non-null   object
 5   income      2602 non-null   float64
 6   statusquo   2683 non-null   float64
 7   vote        2532 non-null   object
dtypes: float64(3), int64(1), object(4)
memory usage: 168.9+ KB

In [18]:
d3["age"].unique()

array([65., 29., 38., 49., 23., 28., 26., 24., 41., 64., 19., 27., 46.,
       36., 22., 20., 30., 67., 50., 55., 18., 58., 34., 43., 53., 32.,
       37., 44., 33., 51., 61., 21., 70., 35., 68., 25., 66., 40., 52.,
       54., 48., 57., 45., 31., 69., 42., 59., 63., 39., 60., 47., 62.,
       56., nan])

In [19]:
d3[d3["age"].isnull()]

     region  population sex  age education   income  statusquo vote
1809     SA      250000   M  NaN         P  15000.0   -1.08507    U

In [20]:
d3.index[1809]

1809

In [22]:
d3.drop(d3.index[1809])

     region  population sex   age education   income  statusquo vote
0         N      175000   M  65.0         P  35000.0    1.00820    Y
1         N      175000   M  29.0        PS   7500.0   -1.29617    N
2         N      175000   F  38.0         P  15000.0    1.23072    Y
3         N      175000   F  49.0         P  35000.0   -1.03163    N
4         N      175000   F  23.0         S  35000.0   -1.10496    N
...     ...         ...  ..   ...       ...      ...        ...  ...
2695      M       15000   M  42.0         P  15000.0   -1.26247    N
2696      M       15000   F  28.0         P  15000.0    1.32950    Y
2697      M       15000   F  44.0         P  75000.0    1.42045    Y
2698      M       15000   M  21.0         S  75000.0    0.18315  NaN
2699      M       15000   M  20.0        PS  35000.0    1.38179    Y

[2699 rows x 8 columns]

In [23]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2700 entries, 0 to 2699
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      2700 non-null   object
 1   population  2700 non-null   int64
 2   sex         2700 non-null   object
 3   age         2699 non-null   float64
 4   education   2689 non-null   object
 5   income      2602 non-null   float64
 6   statusquo   2683 non-null   float64
 7   vote        2532 non-null   object
dtypes: float64(3), int64(1), object(4)
memory usage: 168.9+ KB

In [24]:
d3.shape

(2700, 8)

In [25]:
d3[d3["age"].isnull()]

     region  population sex  age education   income  statusquo vote
1809     SA      250000   M  NaN         P  15000.0   -1.08507    U

In [27]:
mean_age = d3["age"].mean()
mean_age

38.54872174879585

In [28]:
d3.at[1809, "age"] = d3["age"].mean()

In [29]:
d3[d3["age"].isnull()]

Empty DataFrame
Columns: [region, population, sex, age, education, income, statusquo, vote]
Index: []

In [30]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2700 entries, 0 to 2699
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      2700 non-null   object
 1   population  2700 non-null   int64
 2   sex         2700 non-null   object
 3   age         2700 non-null   float64
 4   education   2689 non-null   object
 5   income      2602 non-null   float64
 6   statusquo   2683 non-null   float64
 7   vote        2532 non-null   object
dtypes: float64(3), int64(1), object(4)
memory usage: 168.9+ KB

In [31]:
d3["age"] = d3["age"].astype(int)

In [32]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2700 entries, 0 to 2699
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      2700 non-null   object
 1   population  2700 non-null   int64
 2   sex         2700 non-null   object
 3   age         2700 non-null   int64
 4   education   2689 non-null   object
 5   income      2602 non-null   float64
 6   statusquo   2683 non-null   float64
 7   vote        2532 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 168.9+ KB

In [33]:
d3["education"].unique()

array(['P', 'PS', 'S', nan], dtype=object)

In [35]:
d3["education"].isnull().sum()

11

In [36]:
d3["education"].mode()

0    S
Name: education, dtype: object

In [38]:
d3["education_copy"] = d3["education"]

In [39]:
d3.head()

,region,population,sex,age,education,income,statusquo,vote,education_copy
0,N,175000,M,65,P,35000.0,1.00820,Y,P
1,N,175000,M,29,PS,7500.0,-1.29617,N,PS
2,N,175000,F,38,P,15000.0,1.23072,Y,P
3,N,175000,F,49,P,35000.0,-1.03163,N,P
4,N,175000,F,23,S,35000.0,-1.10496,N,S

In [40]:
d3["education"].mode()[0]

'S'

In [43]:
d3["education_copy"] = d3["education_copy"].fillna(d3["education"].mode()[0])

In [44]:
d3["education_copy"].isnull().sum()

0

In [45]:
d3.drop("education_copy", axis = 1, inplace = True)

In [46]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2700 entries, 0 to 2699
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      2700 non-null   object
 1   population  2700 non-null   int64
 2   sex         2700 non-null   object
 3   age         2700 non-null   int64
 4   education   2689 non-null   object
 5   income      2602 non-null   float64
 6   statusquo   2683 non-null   float64
 7   vote        2532 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 168.9+ KB

In [47]:
d3["education"] = d3["education"].fillna(d3["education"].mode()[0])

In [48]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2700 entries, 0 to 2699
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      2700 non-null   object
 1   population  2700 non-null   int64
 2   sex         2700 non-null   object
 3   age         2700 non-null   int64
 4   education   2700 non-null   object
 5   income      2602 non-null   float64
 6   statusquo   2683 non-null   float64
 7   vote        2532 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 168.9+ KB

In [53]:
d3["vote"].value_counts()

N    889
Y    868
U    588
A    187
Name: vote, dtype: int64

In [54]:
d3["vote"].unique()

array(['Y', 'N', 'U', nan, 'A'], dtype=object)

In [55]:
d3.dropna(subset = "vote", inplace = True)

In [56]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2532 entries, 0 to 2699
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      2532 non-null   object
 1   population  2532 non-null   int64
 2   sex         2532 non-null   object
 3   age         2532 non-null   int64
 4   education   2532 non-null   object
 5   income      2449 non-null   float64
 6   statusquo   2519 non-null   float64
 7   vote        2532 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 178.0+ KB

In [58]:
d3["income"].mean()

33971.00857492854

In [60]:
d3["income"].mode()[0]

15000.0

In [61]:
d3["income"].median()

15000.0

In [62]:
d3["income"] = d3["income"].fillna(d3["income"].mode()[0])

In [63]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2532 entries, 0 to 2699
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      2532 non-null   object
 1   population  2532 non-null   int64
 2   sex         2532 non-null   object
 3   age         2532 non-null   int64
 4   education   2532 non-null   object
 5   income      2532 non-null   float64
 6   statusquo   2519 non-null   float64
 7   vote        2532 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 178.0+ KB

In [65]:
d3["statusquo"].unique()

array([ 1.0082 , -1.29617,  1.23072, ...,  1.3295 ,  1.42045,  1.38179])

In [66]:
d3["statusquo"].isnull().sum()

13

In [67]:
d3["statusquo"].fillna(d3["statusquo"].mean(), inplace = True)

In [68]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2532 entries, 0 to 2699
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      2532 non-null   object
 1   population  2532 non-null   int64
 2   sex         2532 non-null   object
 3   age         2532 non-null   int64
 4   education   2532 non-null   object
 5   income      2532 non-null   float64
 6   statusquo   2532 non-null   float64
 7   vote        2532 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 178.0+ KB

In [ ]:
#now the data is cleaned. let's make some predictions

In [70]:
d3.head()

  region  population sex  age education   income  statusquo vote
0      N      175000   M   65         P  35000.0    1.00820    Y
1      N      175000   M   29        PS   7500.0   -1.29617    N
2      N      175000   F   38         P  15000.0    1.23072    Y
3      N      175000   F   49         P  35000.0   -1.03163    N
4      N      175000   F   23         S  35000.0   -1.10496    N